### ISSUE TITLE
windows compilation trouble

### ISSUE THREAD

**Issue by hardboost** [quarkslab/binmap#4]
Hello. I'd like to try your interesting tool but i have problems with compilation.

I've installed cmake, boost 1.55.0 (link=shared threading=single) to "C:\Libs\boost_1_55_0", zlib to "C:\Libs\zlib-1.2.8", visual studio 2013.
Then executed `cmake -DBoost_DEBUG=ON -G "Visual Studio 12" -DBOOST_ROOT=C:\libs\boost_1_55_0 -DBOOST_LIBRARYDIR=C:\libs\boost_1_55_0\lib32-msvc-12.0 -DZLIB_LIBRARY=C:\libs\zlib-1.2.8 -DZLIB_INCLUDE_DIR=C:\libs\zlib-1.2.8`

When i'm trying to compile 'binmap' project in visual studio i'm getting 2 errors like this:
`C:\Libs\boost_1_55_0\boost/serialization/access.hpp(118): error C2039: 'serialize' : is not a member of 'boost::unordered::unordered_map<std::string,MetadataInfo,boost::hash<std::string>,std::equal_to<T>,std::allocator<std::pair<const K,MetadataInfo>>>'`

Full log:
[binmap.txt](https://github.com/quarkslab/binmap/files/234548/binmap.txt)

I've also tried to compile with precompiled boost 1.56.0/1.59.0/1.60 and visual studio 2010/2015 - nothing helped.
Hope you can help me. Thank you!

**Comment by serge-sans-paille** [comment]
thanks @hardboost for the report, we did have some similar troubles with windows, We'll try to reproduce your issue and provide a workaround!

**Comment by serge-sans-paille** [comment]
turns out we only supported windows through mingw. I take this as an opportunity to have native support, can you tell me if #5 fixes your issue?

**Comment by hardboost** [comment]
those errors disappears, but now linker says `LINK : fatal error LNK1104: cannot open file 'boost_filesystem-vc120-mt-gd-1_55.lib'` thus that i've cmaked it with `set(Boost_USE_MULTITHREADED OFF)`. Anyway even if i added missing file and successfully compile binmap i can't run it. Console says:
```
C:\Tools\binmap\Debug>binmap scan -v2 calc.exe
blacklisting: "/dev"
blacklisting: "/proc"
blacklisting: "/sys"
blacklisting: "/tmp"
ApiSetMap::parse_apisetmap_v2: not implemented
```
and pop-up: 
![image](https://cloud.githubusercontent.com/assets/18659798/14816276/81553804-0bb8-11e6-8e15-c375cd81438f.png)

**Comment by hardboost** [comment]
@serge-sans-paille maybe you need some debug logs from me?

**Comment by serge-sans-paille** [comment]
@hardboost I don't have a windows machine to reproduce your issue right now. Binmap was designed and tested mostly on Linux (but can parse Windows binary from a linux machine)

Good news: One of my colleague should look at it tomorrow. Meanwhile I've pushed a tentative fix, can you tell me if it works on your machine?

Also, can you confirm you no longer have the BOOST_USE_MULTITRHEADED issue and that the default settings are ok with you?

**Comment by hardboost** [comment]
@serge-sans-paille yup, this fix is working. i've got blobs.dat. thank you.

to be honest it's a little strange that you provide CMakeLists.txt with `set(Boost_USE_MULTITHREADED OFF)` because precompiled windows binaries are multi-threaded only.
single-threaded compilation still requires `boost_filesystem-vc120-mt-gd-1_55.lib` (on file /src/collectors/pe/collector.cpp). don't know why, maybe my boost compilation was incorrect, because project's linking settings is ok.
multi-threaded compilation works well.

**Comment by serge-sans-paille** [comment]
Happy it works! I'll set the default to ON for Windows and OFF for linux, as it seems to reflect the most standard config.

**Comment by serge-sans-paille** [comment]
@hardboost I've updated the cmake (and amended a commit for better commit message). If you confirm this solves your issue, I'll merge it.

**Comment by hardboost** [comment]
@serge-sans-paille cmake is good now. 

almost compile all. only blobmap has an error:
```1>blobmap_wrapper.obj : error LNK2019: unresolved external symbol "class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl operator<<(class std::basic_ostream<char,struct std::char_traits<char> > &,struct NodeDiff const &)" (??6@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@std@@AAV01@ABUNodeDiff@@@Z) referenced in function "private: bool __thiscall boost::detail::lexical_istream_limited_src<char,struct std::char_traits<char>,1,2>::shl_input_streamable<struct NodeDiff const >(struct NodeDiff const &)" (??$shl_input_streamable@$$CBUNodeDiff@@@?$lexical_istream_limited_src@DU?$char_traits@D@std@@$00$01@detail@boost@@AAE_NABUNodeDiff@@@Z)
1>C:\Tools\binmap\Debug\blobmap.dll : fatal error LNK1120: 1 unresolved externals```
[blobmap.txt](https://github.com/quarkslab/binmap/files/240509/blobmap.txt)
boost 1.55.0 has the same effect.
probably should forget about it and try to compile with mingw :(

also projects `mylib` and `otherlib` generate dynamic libraries but `myprog` and `mynewprog` are trying to link with static libraries `mylib.lib` and `otherlib.lib`. Setting configuration type to static library is resolving this problem, i think.

**Comment by serge-sans-paille** [comment]
On Thu, Apr 28, 2016 at 05:46:46AM -0700, hardboost wrote:
> probably should forget about it and try to compile with mingw :(

If you don't mind going on with the VS studio build, it helps a lot
trying to debug the build on that platform! I'll have a look to your
issue tomorrow.

**Comment by hardboost** [comment]
@serge-sans-paille any updates on VS build?

**Comment by serge-sans-paille** [comment]
On Tue, May 03, 2016 at 05:32:17AM -0700, hardboost wrote:
> @serge-sans-paille any updates on VS build?

Not yet, I'm pretty busy giving a formation right now... I'll keep you
in touch!

**Comment by neitsa** [comment]
@hardboost : Just checked the problem with VS 2015, but that should also work with previous versions.

My rig:
    - VS 2015
    - Python 2.7
    -  Boost 1.60.0
    - Zlib 1.2.8

On blobmapp.cpp line 37 (see https://github.com/quarkslab/binmap/blob/master/src/blobmap.cpp#L37 ) remove the `#ifdef` (or set it as `#ifndef`, but removing it is preferable.

Do the same for the `#ifdef` at line 67 (see https://github.com/quarkslab/binmap/blob/master/src/blobmap.cpp#L67 )

IIRC, those lines where disabled for Windows as there was a problem compiling them on VS; but that should work now.

You should be able to compile blobmap and get the blobmap.dll binary.

Let us know if that work.

**Comment by hardboost** [comment]
@neitsa great! finally compile it :) thanks you
VS 2013 + boost 1.55.0 works well.

**Comment by neitsa** [comment]
@hardboost  Thank you very much for your feedback!

**Comment by serge-sans-paille** [comment]
Thanks a lot @neitsa ! I've updated the PR with your change, if @hardboost confirms it compiles, then I'll accept it.

**Comment by hardboost** [comment]
@serge-sans-paille Compilation from scratch is successfull, except for `mynewprog` and `myprog` because of `LINK : fatal error LNK1104: cannot open file 'Debug\mylib.lib'`. I've mentioned it before:
> also projects mylib and otherlib generate dynamic libraries but myprog and mynewprog are trying to link with static libraries mylib.lib and otherlib.lib. Setting configuration type to static library is resolving this problem, i think.

Everything else is OK. Good job!

**Comment by serge-sans-paille** [comment]
@hardboost I just merged #5 , looks like I can close this issue?

**Comment by hardboost** [comment]
@serge-sans-paille yes, thank you.
